services:
  server-app:
    container_name: dify-hub-server-app
    build:
      context: .
      dockerfile: packages/server/Dockerfile
      target: dev
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
      mailpit:
        condition: service_healthy
    restart: always
    tty: true
    init: true
    ports:
      - 8080:8080
      - 5555:5555
    volumes:
      - ./packages/server:/app

  client-app:
    container_name: dify-hub-client-app
    build:
      context: .
      dockerfile: packages/client/Dockerfile
      target: dev
    restart: always
    tty: true
    init: true
    ports:
      - 3000:3000
    depends_on:
      - server-app
    volumes:
      - ./packages/client:/app

  db:
    image: postgres:16
    container_name: dify-hub-db
    restart: always
    environment:
      POSTGRES_DB: difyhub
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: Asia/Tokyo
    command: >
      postgres -c 'max_connections=100'
               -c 'shared_buffers=128MB'
               -c 'work_mem=4MB'
               -c 'maintenance_work_mem=64MB'
               -c 'effective_cache_size=4096MB'
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-h', 'db', '-U', 'dify_hub', '-d', 'dify_hub' ]
      interval: 1s
      timeout: 3s
      retries: 60
    ports:
        - 15432:5432

  minio:
    image: minio/minio
    container_name: dify-hub-minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./volumes/minio:/export
    environment:
      MINIO_ROOT_USER: minio_root
      MINIO_ROOT_PASSWORD: minio_password
    command: server /export --console-address ":9001"

  mailpit:
    image: axllent/mailpit
    container_name: dify-hub-mailpit
    ports:
      - 1025:1025
      - 8025:8025
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8025"]
      interval: 10s
      timeout: 5s
      retries: 5
