services:
  # server-app:
  #   container_name: dify-hub-server-app
  #   build:
  #     context: .
  #     dockerfile: packages/server/app/Dockerfile
  #     target: dev
  #   depends_on:
  #     - mysql
  #     - minio
  #     - mailpit
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./packages/server:/app
  #   networks:
  #     - dify_hub

  client-app:
    container_name: dify-hub-client-app
    build:
      context: .
      dockerfile: packages/client/Dockerfile
      target: dev
    restart: always
    tty: true
    init: true
    ports:
      - 3000:3000
    volumes:
      - ./packages/client:/app
    networks:
      - dify_hub

  # db:
  #   image: postgres:15-alpine
  #   container_name: dify-hub-db
  #   restart: always
  #   environment:
  #     PGUSER: ${PGUSER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     PGDATA: -/var/lib/postgresql/data/pgdata
  #   command: >
  #     postgres -c 'max_connections=100'
  #              -c 'shared_buffers=128MB'
  #              -c 'work_mem=4MB'
  #              -c 'maintenance_work_mem=64MB'
  #              -c 'effective_cache_size=4096MB'
  #   volumes:
  #     - ./volumes/db/data:/var/lib/postgresql/data
  #   networks:
  #     - dify_hub

  # minio:
  #   image: minio/minio:RELEASE.2023-03-20T20-16-18Z
  #   container_name: dify-hub-minio
  #   command: minio server /minio_data --console-address ":9001"
  #   volumes:
  #     - ./volumes/minio:/minio_data
  #   environment:
  #     - MINIO_ROOT_USER=minio_root
  #     - MINIO_ROOT_PASSWORD=minio_password
  #   ports:
  #     - "9000:9000"
  #     - "9090:9090"
  #   networks:
  #     - dify_hub

  # mailpit:
  #   image: axllent/mailpit
  #   container_name: dify-hub-mailpit
  #   ports:
  #     - 1025:1025
  #     - 8025:8025
  #   networks:
  #     - dify_hub

networks:
  dify_hub:
    external: true
